// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70yiGznZZJ3WPqx70CN8chZ8CmX33WJU',
    appId: '1:236743567766:web:3833b605d088cc361c95b7',
    messagingSenderId: '236743567766',
    projectId: 'alltypes-bf28a',
    authDomain: 'alltypes-bf28a.firebaseapp.com',
    storageBucket: 'alltypes-bf28a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKXGAevSK5d4_56viiIWyJOk1gIZJZvcI',
    appId: '1:236743567766:android:c21cda4162a4af701c95b7',
    messagingSenderId: '236743567766',
    projectId: 'alltypes-bf28a',
    storageBucket: 'alltypes-bf28a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8d47pDUTti2fC8utIcgIYPewrNbtZUA',
    appId: '1:236743567766:ios:49b0c8a5da2768c01c95b7',
    messagingSenderId: '236743567766',
    projectId: 'alltypes-bf28a',
    storageBucket: 'alltypes-bf28a.appspot.com',
    iosClientId: '236743567766-05d3p52d8tu6c0f7se24trak8tddcihm.apps.googleusercontent.com',
    iosBundleId: 'com.example.allregistrationtypes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8d47pDUTti2fC8utIcgIYPewrNbtZUA',
    appId: '1:236743567766:ios:e9f98697a5c5ca6c1c95b7',
    messagingSenderId: '236743567766',
    projectId: 'alltypes-bf28a',
    storageBucket: 'alltypes-bf28a.appspot.com',
    iosClientId: '236743567766-iaiia0jf57corthb4pisuadneaqndftb.apps.googleusercontent.com',
    iosBundleId: 'com.example.allregistrationtypes.RunnerTests',
  );
}
